name: "RoleRevoke1"

on:
  
  workflow_dispatch:
  
  push:
  
env:
  client_id: ${{ secrets.CLIENT_ID }}
  client_secret: ${{ secrets.CLIENT_SECRET }}
  url: ${{ secrets.URL }}
  
jobs:
 
   build:
     
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - run: python RoleScript.py
